# server/render.yaml
services:
  - type: web
    name: gary-server
    env: node
    region: oregon
    plan: free
    branch: Dev2  # Changed from main to Dev2 to match your current branch
    buildCommand: npm install && npm run build  # Explicitly install dependencies before building
    startCommand: node dist/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production