# server/render.yaml
services:
  - type: web
    name: gary-server
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && tsc --project tsconfig.json
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production